'''Tests for PendulumRL: the SB3-free NumPy MLP controller must reproduce the
trained SAC policies' deterministic actions (golden fixtures from
``fixtures/rl_golden.json``, generated by SB3 ``predict(deterministic=True)``),
plus the action-repeat hold behavior.'''

import json
import math
import os

import numpy as np
import pytest

from safe_control_gym.controllers.pendulum_rl.pendulum_rl import PendulumRL
from safe_control_gym.envs.gym_control.inverted_pendulum import InvertedPendulum

FIX = os.path.join(os.path.dirname(__file__), 'fixtures')
GOLDEN = json.load(open(os.path.join(FIX, 'rl_golden.json')))
MODELS = sorted(GOLDEN.keys())  # v1_strong, v1_weak, ... v4_weak


def env_func(**kwargs):
    cfg = dict(ctrl_freq=100, pyb_freq=100, randomized_init=False, cost='quadratic')
    cfg.update(kwargs)
    return InvertedPendulum(**cfg)


@pytest.mark.parametrize('model', MODELS)
def test_forward_matches_sb3_golden(model):
    ctrl = PendulumRL(env_func, model_path=model, action_repeat=1)
    for pair in GOLDEN[model]:
        obs = np.array([pair['theta'], pair['thetadot']], dtype=np.float64)
        u = ctrl.select_action(obs)
        assert np.asarray(u).shape == (1,)
        np.testing.assert_allclose(float(np.asarray(u).reshape(-1)[0]), pair['action'], atol=1e-5,
                                   err_msg=f'{model}: action diverged from SB3 predict')
    ctrl.close()


def test_action_repeat_holds_then_requeries():
    ctrl = PendulumRL(env_func, model_path='v1_strong', action_repeat=4)
    ctrl.reset()
    a0 = ctrl.select_action(np.array([1.0, 0.0]))          # query
    held = [ctrl.select_action(np.array([2.0, 1.0])),      # held
            ctrl.select_action(np.array([-1.0, -2.0])),    # held
            ctrl.select_action(np.array([0.5, 0.5]))]      # held
    for a in held:
        np.testing.assert_allclose(a, a0)
    a4 = ctrl.select_action(np.array([0.5, 0.5]))          # re-query
    fresh = PendulumRL(env_func, model_path='v1_strong', action_repeat=1)
    fresh.reset()
    np.testing.assert_allclose(a4, fresh.select_action(np.array([0.5, 0.5])), atol=1e-9)
    ctrl.close()
    fresh.close()


def test_obs_normalizer_is_identity_and_freezable():
    ctrl = PendulumRL(env_func, model_path='v1_strong')
    obs = np.array([0.3, -0.4])
    np.testing.assert_allclose(ctrl.obs_normalizer(obs), obs)
    ctrl.obs_normalizer.set_read_only()  # traj-gen scripts call this
    ctrl.close()


def test_action_within_u_sat():
    ctrl = PendulumRL(env_func, model_path='v4_strong', action_repeat=1)
    u_sat = ctrl.env.u_sat
    rng = np.random.default_rng(0)
    for _ in range(30):
        state = rng.uniform([-math.pi, -6.0], [math.pi, 6.0])
        u = float(np.asarray(ctrl.select_action(state)).reshape(-1)[0])
        assert abs(u) <= u_sat + 1e-9
    ctrl.close()
