'''Golden rollout fidelity for cartpole and both quadrotors.

Fixtures were generated by tests/fixtures/generate_env_rollouts.py under
gymnasium 0.28, before the Gymnasium migration. They must reproduce exactly.

Cartpole and both quadrotors are PyBullet-backed: ``env.state`` is read back
from the physics client, not consumed by it, so injecting a chosen x0 via
``env.state = ...`` between steps does not seed the next ``step()``. Each
scenario is instead reproduced by resetting with the fixture's recorded
seed; the recorded ``x0`` is checked as a reset-determinism sanity check.
'''
import json
import os

import numpy as np
import pytest

from safe_control_gym.utils.registration import make

FIX = os.path.join(os.path.dirname(__file__), 'fixtures')

CASES = ['cartpole_rollouts.json',
         'quadrotor_2d_rollouts.json',
         'quadrotor_3d_rollouts.json']


@pytest.mark.parametrize('fixture', CASES)
def test_rollouts_match_golden(fixture):
    with open(os.path.join(FIX, fixture)) as handle:
        data = json.load(handle)
    env = make(data['params']['task'], **data['params']['task_config'])
    for scenario in data['scenarios']:
        env.reset(seed=scenario['seed'])
        np.testing.assert_allclose(env.state, scenario['x0'], atol=1e-9)
        for act, expected in zip(scenario['actions'], scenario['states']):
            env.step(np.asarray(act, dtype=np.float64))
            np.testing.assert_allclose(env.state, expected, atol=1e-9)
    env.close()
